#!/bin/sh
# Simple script which configure Xfce environment for a fresh user
# Author: tpg@mandriva.org
# Licensed under GPL terms

MDV_FLAVOUR=`echo $META_CLASS`
USER_DESKTOP=`xdg-user-dir DESKTOP`
DESKTOP_FILE=$HOME/.config/autostart/xfce4-firstrun.desktop

if [ `whoami` = "root" ]; then
    echo "xfce4-firstrun: not supported for superuser."
    exit || 0
else
    if [ ! -e $DESKTOP_FILE ]; then
	echo "xfce4-firstrun: localised desktop folder exists."
	if [ ! -d $HOME/.config/autostart ]; then
	mkdir -p $HOME/.config/autostart
	fi

cat > $HOME/.config/autostart/xfce4-firstrun.desktop << EOF
[Desktop Entry]
Hidden=true
EOF
#

	if [ $MDV_FLAVOUR = "download" -o $MDV_FLAVOUR = "desktop" ]; then
	    if [ ! -e $USER_DESKTOP/register.desktop ]; then
		cp -f /usr/share/mdk/desktop/free/register.desktop $USER_DESKTOP 2> /dev/null
	    fi

	    if [ ! -e $USER_DESKTOP/upgrade.desktop ]; then
		cp -f /usr/share/mdk/desktop/one/upgrade.desktop $USER_DESKTOP 2> /dev/null
	    fi

	    if [ ! -e $USER_DESKTOP/mandriva-draklive-install.desktop ]; then
		cp -f /usr/share/applications/mandriva-draklive-install.desktop $USER_DESKTOP 2> /dev/null
	    fi
		if [ "$(pidof xfdesktop)" ]; then 
		    xfdesktop --reload 1> /dev/null; echo "xfce4-firstrun: xfdesktop reloaded.";
		fi
	    exit || 0

	else
	    if [ ! -e $USER_DESKTOP/register.desktop ]; then
		cp -f /usr/share/mdk/desktop/powerpack/register.desktop $USER_DESKTOP 2> /dev/null
	    fi

	    if [ ! -e $USER_DESKTOP/mandriva-draklive-install.desktop ]; then
		cp -f /usr/share/applications/mandriva-draklive-install.desktop $USER_DESKTOP 2> /dev/null
	    fi
		if [ "$(pidof xfdesktop)" ]; then 
		    xfdesktop --reload 1> /dev/null; echo "xfce4-firstrun: xfdesktop reloaded.";
		fi
	    exit || 0
	fi
    else echo "xfce4-firstrun: make sure you have installed xdg-user-dirs-gtk and xdg-user-dir packages."
    fi

fi

#EOF
