#!/bin/bash

MDV_FLAVOUR=`echo $META_CLASS`
USER_DESKTOP=`xdg-user-dir DESKTOP`
DESKTOP_FILE=$HOME/.config/autostart/xfce4-update-config.desktop

if [ `whoami` = "root" ]; then
    echo "Not supported for root user"
    exit || 0
else
    if [ ! -e $DESKTOP_FILE ]; then
	echo "Localised desktop folder exists."
	if [ ! -d $HOME/.config/autostart ]; then
	mkdir -p $HOME/.config/autostart
	fi

cat > $HOME/.config/autostart/xfce4-update-config.desktop << EOF
[Desktop Entry]
Hidden=true
EOF
#

	if [ $MDV_FLAVOUR = "download" -o $MDV_FLAVOUR = "desktop" ]; then
	    if [ ! -e $USER_DESKTOP/register.desktop ]; then
		cp -f /usr/share/mdk/desktop/free/register.desktop $USER_DESKTOP
	    fi

	    if [ ! -e $USER_DESKTOP/upgrade.desktop ]; then
		cp -f /usr/share/mdk/desktop/one/upgrade.desktop $USER_DESKTOP
	    fi
	    
	    if [ ! -e $USER_DESKTOP/mandriva-draklive-install.desktop ]; then
		cp -f /usr/share/applications/mandriva-draklive-install.desktop $USER_DESKTOP
	    fi

	    xfdesktop --reload
	    exit || 0

	else
	    if [ ! -e $USER_DESKTOP/register.desktop ]; then
		cp -f /usr/share/mdk/desktop/powerpack/register.desktop $USER_DESKTOP
	    fi
	    
	    if [ ! -e $USER_DESKTOP/mandriva-draklive-install.desktop ]; then
		cp -f /usr/share/applications/mandriva-draklive-install.desktop $USER_DESKTOP
	    fi
	    
	    xfdesktop --reload
	    exit || 0
	fi
    fi
fi

#EOF
